---
include:
  - project: "article714/build-tools"
    ref: master
    file: "ci/odoo-modules-pipeline.yml"

variables:
  # CI_DEBUG_TRACE: "true"
  PYTHON_VERSION: "3.9"
  DEBIAN_VERSION: slim
  ODOO_VERSION: 15.0-preview
  POSTGRESQL_IMAGE: postgres:11
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo
  POSTGRES_DB: testdb
  POSTGRES_HOST_AUTH_METHOD: trust

# -----------------------------------------
# Tests
#

test_coreff_base_install:
  extends: .test_module_installation
  variables:
    MODULE_NAMES: coreff_base

test_coreff_societecom:
  extends: .install_and_test_module
  variables:
    MODULE_NAMES: coreff_base_l10n_fr_siret,coreff_societecom
